{% set name = "pytest-excel" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-excel-{{ version }}.tar.gz
  sha256: 4b8f86a4f04cc7e6da3ec9f308f8fcc77a4243313c3f64d330e64c43137d5eaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest >=3.6
    - openpyxl

test:
  imports:
    - pytest_excel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ssrikanta/pytest-excel
  summary: pytest plugin for generating excel reports
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
